### ISSUE TITLE
is this working with Rails 4 and last version of Tire?

### ISSUE THREAD

**Issue by ssoulless** [leschenko/elasticsearch_autocomplete#13]

**Comment by leschenko** [comment]
`elasticsearch_autocomplete` doesn't depend on rails.
Yes, with gem works with latest tire and activemodel 4.2.0 (activerecord 4.2.0).
But latest tire doesn't officially support elasticsearch 1.x, so there is a branch built on top of new official ruby elasticsearch client `elasticsearch-ruby` https://github.com/leschenko/elasticsearch_autocomplete/tree/elasticsearch-ruby
