### ISSUE TITLE
How to specify an alternative host/port?

### ISSUE THREAD

**Issue by arthurcolle** [leschenko/elasticsearch_autocomplete#14]
I am deploying to Heroku and was wondering how to specify an alternative host (bonsai.io)? 

Also, is there a smooth way of not using Tire to import the model data from Postgres to ES?

Thanks

**Comment by leschenko** [comment]
This version uses tire to interact with elasticsearch, so should configure es host there.
> Also, is there a smooth way of not using Tire to import the model data from Postgres to ES?

What did you mean?

**Comment by arthurcolle** [comment]
I answered my own question a while ago and forgot to close this issue. Thanks very much! :)
