### ISSUE TITLE
Error Running Example | analyzer on field [ac_term] must be set when search_analyzer is set

### ISSUE THREAD

**Issue by lenriquez** [leschenko/elasticsearch_autocomplete#16]
I keep getting this error when I try to create the index by running the following command:

$ rake autocomplete
[ERROR] There has been an error when creating the index -- elasticsearch returned:
400 : {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"analyzer on field [ac_term] must be set when search_analyzer is set"}],"type":"mapper_parsing_exception","reason":"mapping [autocomplete]","caused_by":{"type":"mapper_parsing_exception","reason":"analyzer on field [ac_term] must be set when search_analyzer is set"}},"status":400}
[ERROR] There has been an error when creating the index -- elasticsearch returned:
400 : {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"analyzer on field [ac_term] must be set when search_analyzer is set"}],"type":"mapper_parsing_exception","reason":"mapping [autocomplete]","caused_by":{"type":"mapper_parsing_exception","reason":"analyzer on field [ac_term] must be set when search_analyzer is set"}},"status":400}

Thanks for your help!

**Comment by leschenko** [comment]
What is your model elasticsearch_autocomplete configuration and mapping?
What elasticsearch version do you use?

**Comment by lenriquez** [comment]
This is what I got:
    -The version is of elasticsearch is 2.0.0 
    -when I executed curl 'localhost:9200/_cat/indices?v' I got this
    yellow open   nilclass_autocompletes   5   1        377            0     60.8kb         60.8kb 
    curl -XGET 'http://localhost:9200/nilclass_autocompletes/_mapping'
{"nilclass_autocompletes":{"mappings":{"autocomplete":{"properties":{"freq":{"type":"long"},"term":       {"type":"string"}}}}}}
     - curl -XGET 'http://localhost:9200/nilclass_autocompletes/_settings'
{"nilclass_autocompletes":{"settings":{"index":{"creation_date":"1447154748870","number_of_shards":"5","number_of_replicas":"1","uuid":"FAZY6tDtRz2aYFKC0X09HQ","version":{"created":"2000099"}}}}}

**Comment by leschenko** [comment]
I have not tested elasticsearch_autocomplete with elasticsearch 2.0.0 yet.
Seems that current version is not compatible with es 2.0.
I will take a look at this.

**Comment by niuage** [comment]
I think that the issue is that you now need to use `analyzer` instead of `index_analyzer` in the mapping.

Ex:
```
defaults.merge(index_analyzer: 'ac_edge_ngram', boost: 3)
```

I had an old mapping using index_analyzer, and replacing the option with just `analyzer` worked.

**Comment by alexrogers** [comment]
just ran into the same issue after running a `brew upgrade`.  The simple fix was to use an older version of elasticserach so i did a `brew install elasticsearch17` and everything works again.

**Comment by niuage** [comment]
Sure, but I don't see why he would turn his back to the greatness of ES 2 when there's another simple fix ;)

**Comment by leschenko** [comment]
First of all sorry for delay.
Released version 0.1.6 with es 2.0 compatibility fixes
