### ISSUE TITLE
Improvement Suggestion

### ISSUE THREAD

**Issue by MojoDeMedici** [leschenko/elasticsearch_autocomplete#2]
@leschenko

How do you think we can modify the ac_search method in order to provide an optional filter, that avoid to return the current user in the list?

I have this working in my model, but I can't figure out how let it working with your gem.
I have it directly in a tire search, but I would like to incorporate directly in the ac_search method, maybe using an optional parameter to pass directly to the method (need to be passed in the method and not through the option, due to the impossibility to access a current user from the user model):
## (1) This will filter the results returned by elasticsearch, and exclude the current user (this tire method is present in the user model)

filter :ids, :values => self.without_current_user(user).map(&:id)
## (2) Method to exclude a specific user from all the users (the current user) - this will allow to pass an instance of the current user (e.g @user)

  def self.without_current_user(user)
    self.where("users.id != ?", user.id)
  end

Looking forward to hear from you.

Best
Dinuz

**Comment by ghost** [comment]
@leschenko is there a way to filter the items that get indexed? I see the example with `skip_settings` but I'm not getting it ... what if I wanted to do something arbitrary like only include records where name starts with "Q"
